BOARD_SIZE = BOARD_WIDTH, BOARD_HEIGHT = 420, 420
DEAD_COLOR = 0, 0, 0
ALIVE_COLOR = 255, 0, 0
CELL_SIZE = (10, 10)

NUM_COLS = int(BOARD_WIDTH/CELL_SIZE[0])
NUM_ROWS = int(BOARD_HEIGHT/CELL_SIZE[1])
